### ISSUE TITLE
Unable to use mixed data sources

### ISSUE THREAD

**Issue by veebkolm** [SAP/alm-plug-in-for-grafana#102]
We would like to consolidate key data from multiple sources onto a single dashboard. For that, Grafana enables to use multiple data sources. Attempting to use those, only the last query works and first data source(s) return an error.

Plugin commit: bc0ddfb74e79bc64f8b23a3bf100d635b87c7ec9
Grafana version: 10.1.2

![Screenshot from 2023-11-02 14-16-57](https://github.com/SAP/alm-plug-in-for-grafana/assets/25956365/af33a6cb-90a8-497b-867e-a281a6330019)

**Comment by veebkolm** [comment]
https://stackoverflow.com/questions/46378310/mixing-multiple-data-sources-in-the-same-panel

**Comment by vienlam** [comment]
> https://stackoverflow.com/questions/46378310/mixing-multiple-data-sources-in-the-same-panel

I see. Thanks for sharing. We have overlooked this feature. I will let you know if there's any update on this.

**Comment by vienlam** [comment]
Hi @veebkolm ,

I have just submitted a minor fix to the plug-in. Please update your project and rebuild it to see if it works.

**Comment by andreacampo** [comment]
Closed by latest release v1.2.1.
