### ISSUE TITLE
alm-plug-in-for-grafana on Cloud version of Grafana

### ISSUE THREAD

**Issue by SM885** [SAP/alm-plug-in-for-grafana#103]
Hello,

How can this plugin **alm-plug-in-for-grafana** be accessed in the cloud version of Grafana?

Thanks.

**Comment by vienlam** [comment]
Hi,

This plug-in does not work with cloud version of Grafana due to some constraints.

Best regards

**Comment by SM885** [comment]
Thank you so much for  the information.
Is there any workaround available to connect to SAP Cloud ALM from Cloud version of Grafana ?

**Comment by vienlam** [comment]
> Thank you so much for the information. Is there any workaround available to connect to SAP Cloud ALM from Cloud version of Grafana ?

We currently have no other option in cloud version of Grafana as far as I know.

Maybe @andreacampo can provide some insides?
