### ISSUE TITLE
Add packaged plugin to release 

### ISSUE THREAD

**Issue by Breee** [SAP/alm-plug-in-for-grafana#105]
Greetings,

Would it be possible to package and attach the plugin to the release? 
Or even push it to the grafana marketplace?

kind regards

**Comment by andreacampo** [comment]
Hello,

Unfortunately we are not allowed to release built artifacts in this project.
Furhtermore, only signed plugin can be pushed to the grafana marketplace. But for this type of plugin (connecting to a proprietary technology like SAP Cloud ALM) the signing process has licensing consequences that would have an impact on the current distribution/availability process.

Best Regards,

Andrea
