### ISSUE TITLE
Adding support for alerts

### ISSUE THREAD

**Issue by jwislakPG** [SAP/alm-plug-in-for-grafana#108]
Currently plugin don't support alerting:
![image](https://github.com/SAP/alm-plug-in-for-grafana/assets/144685141/e3a72e30-a7a7-409c-a862-33a4b5de557c)
Do you plan add support for alerts?

**Comment by andreacampo** [comment]
Hello,

Support for Alerts is not planned at the moment.

Best Regards,

Andrea
