### ISSUE TITLE
alm-plug-in-for-grafana --> An unexpected error happened during exploring Data Providers

### ISSUE THREAD

**Issue by mehusa82** [SAP/alm-plug-in-for-grafana#109]
Hello everyone,
we are using the Grafana plugin for SAP Cloud ALM and always get the error message "An unexpected error happened" when using the data provider (ALM Business Process Monitoring - KPI_HISTORY_TOTALS). In the Dev Tools under Network I see the following error regarding "PRECONDITION_REQUIRED : Missing filter for dimension 'kpiId'", but I cannot define the filter because the unexpected error appears first.
{
    "error": {
        "code": "PRECONDITION_REQUIRED",
        "message": "PRECONDITION_REQUIRED : Missing filter for dimension 'kpiId'",
        "target": "",
        "details": [
            {
                "code": "x-correlationid",
                "message": "d0b2e6fe-bc37-4a4c-6ee6-bb0e9917ab8e"
            }
        ]
    }
}
With (ALM Real User Monitoring - DP_RUM_REQUEST_TYPES) the unexpected error also appears, with the info "PRECONDITION_REQUIRED : At most 5 services or systems allowed in scope. Add filters to restrict number of services or systems.", but again the unexpected error occurs before I can define a filter. 
{
    "error": {
        "code": "PRECONDITION_REQUIRED",
        "message": "PRECONDITION_REQUIRED : At most 5 services or systems allowed in scope. Add filters to restrict number of services or systems.",
        "target": "",
        "details": [
            {
                "code": "x-correlationid",
                "message": "f906cc9a-2e9f-4b14-7c16-045ca9dce2ef"
            }
        ]
    }
}
The service instance has the required scope calm-api.bm.read and calm-api.rum.read

Thanks & best regards,
Sascha

**Comment by andreacampo** [comment]
Hello,

The error means that one of the mandatory filters is missing.
In case of BPM this is the "Kpid" which describes the metric to be displayed:

<img width="715" alt="image" src="https://github.com/SAP/alm-plug-in-for-grafana/assets/71137661/55f972f0-42d9-48b9-92c8-86b44f19952a">

When mandatory filters are missing, you get the displayed error as explained here:

https://help.sap.com/docs/cloud-alm/apis/business-process-monitoring-analytics-api?locale=en-us

From the "Restriction" section:

`If the kpiID is not selected as filter, an HTTP 428 exception is raised.`

Best Regards,

Andrea
