### ISSUE TITLE
Grafana install on windows

### ISSUE THREAD

**Issue by Kim-Allan** [SAP/alm-plug-in-for-grafana#110]
I have installed the data source sap-alm.dp-api-datasource plud in on grafana. 

I do also see the plud in, but when I press blue button add new data source, and it add's it. There is no input fields. Only there is button delete and back, which should be in the button of the screen, after all the input fields.

I have added parameter allow_loading_unsigned_plugins=sap-alm-dp-api-datasource both in file defaults.ini and custom.ini (which is a copy of defaults.ini. I do also see the parameter in settings in grafana under pludins. So I think that is ok.

I have changed app_mode to development, instead of production. I read somewhere that was needed, to run unsigned plugins. That is not helping much.

I ran yarn install and yarn build, and that seems to work okay. Some warnings, but no errors. But when building with yarn build it says enviroment production. So I have tried yarn dev, but then it does not finish compiling. So not sure, what is right.

If i press F12 in browser, when I try to add the datasource, I see under console it says.

Failed to load resource: the server responded with a status of 404 (Not Found)
:3000/api/gnet/plugins/sap-alm-dp-api-datasource:1 
         
      
{
  "code": "NotFound",
  "message": "plugin not found",
  "requestId": "0c934ea3-03f0-4409-ba59-272b10be38d0"
}

So something is wrong, but is it parameter, which I beleave is ok, since it can not find it?
Is it yarn build, or yarn dev, which is needed?
So app_mode be developemnt or production ?

Dist files, are not modified yet. I would go with option, that I keep "zudr", and give information in the plug in.

Any ideas, what it could be?

**Comment by andreacampo** [comment]
Closed by #112
