### ISSUE TITLE
Cloud ALM API not found

### ISSUE THREAD

**Issue by Kim-Allan** [SAP/alm-plug-in-for-grafana#115]
This API is the only API I can get to work
https://mycloudalm.eu10.alm.cloud.sap/api/calm-analytics/v1

If I try any of these of these API's, then it says not found, when I create a new datasource in grafana
https://mycloudalm.eu10.alm.cloud.sap/api/calm-landscape/v1
https://mycloudalm.eu10.alm.cloud.sap/api/calm-logs/v1
https://mycloudalm.eu10.alm.cloud.sap/api/calm-traces/v1
https://mycloudalm.eu10.alm.cloud.sap/api/calm-event-situations/v1

I am sure, the connection details is correct, since I can make analytics work, but why all others says not found? Any ideas ?

**Comment by andreacampo** [comment]
Hello Allan,

https://mycloudalm.eu10.alm.cloud.sap/api/calm-analytics/v1 is the one to be used when configuring your datasource in grafana.
The other APIs are used for other purposes, you can find additional documentation [here](https://help.sap.com/docs/cloud-alm/apis/api-reference?locale=en-us).

Best Regards,

Andrea

**Comment by Kim-Allan** [comment]
Hmm. But how do I then make graph for CPU which are in metrics API. Or check if data collection is running which are in other API’s ? 

I was expecting I could make a dashboard in grafana which data from different parts of cloud ALM. Not only analytic? 
any good solution for that ?

**Comment by andreacampo** [comment]
Hello Allan,

You can get all the metrics using the analytic api (the one supported by the Grafana Plugin).
In fact, the (outbount) "metrics API" you are referring to, is  simply used to translate the results of the "Analytics API" into output compatible with the Open Telemetry Protocol. 
But the metrics you can get from both APIs are the same ones produced by the different SAP Cloud ALM Applications.
For example, here is a panel showing CPU related metrics from an ABAP System monitored by a SAP Cloud ALM Tenant.

<img width="1146" alt="image" src="https://github.com/SAP/alm-plug-in-for-grafana/assets/71137661/3ec922dc-8996-47de-81cf-40f07c5d307d">

This is done using the Health Monitoring data provider available in the analytics api.

Best Regards,

Andrea

**Comment by Kim-Allan** [comment]
Just so I get it right. Analytics contains all data which are available on the other API’s ? 
like landscape api, event api all of these the data is also in analytic api ?

**Comment by Kim-Allan** [comment]
To be more specific, what I wanted was. To make a dashboard, with all kind of small widgets. As I could read, from the different API, Logs API, metrics API, Event API ect. I could get all kind of data form there. 
One small widget could be. Is data collections running. 
![image](https://github.com/SAP/alm-plug-in-for-grafana/assets/169995484/ee70ff5f-8eaa-47e9-a6f8-bdd220d42d40)

And all kind of small wigets, but I am not sure, I can get that data from analytic widget ?

**Comment by andreacampo** [comment]
Hello Allan,

These are the supported Data Providers by the Analytics API:

- Business Process Monitoring Analytics API
- Configuration and Security Analysis Analytics API
- Defects Analytics API
- Exception Monitoring Analytics API
- Health Monitoring Analytics API
- Integration Monitoring Analytics API
- Job and Automation Monitoring Analytics API
- Monitoring Events Analytics API
- Projects Analytics API
- Real User Monitoring Requests Type Analytics API
- Requirements Analytics API
- Status Events Analytics API
- Tasks Analytics API
- Test Execution Analytics API
- Synthetic User Monitoring Analytics API

There are no Logs or Landscape related data in there and, as far as I know, it's not possible to get the status of the data collection.

Best Regards,

Andrea
