### ISSUE TITLE
SAP ALM plugin is not detected in Grafana

### ISSUE THREAD

**Issue by suren7123** [SAP/alm-plug-in-for-grafana#118]
Hello

I tried installing the ALM plugin using the instructions provided in Github but I couldn't find the plugin in Grafana user interface.

We have Grafana v10.0.3 installed in 2 instances(HA) which are in active-active mode.
Its an Enterprise version and its installed in RHEL 9.

We installed the plugin in both the instances but we couldn't find the ALM plugin under New Data source.

Thanks 
Suren

**Comment by andreacampo** [comment]
Hello Suren,

Have you set the parameter allow_loading_unsigned_plugins=sap-alm-dp-api-datasource in the grafana.ini?

Best Regards,

Andrea

**Comment by suren7123** [comment]
Yes Andrea, we already added.
Also, I want to inform that we have built the plugin in different server and copied the dest folder to Grafana server (inside the sap folder in plugin directory).

**Comment by andreacampo** [comment]
Hello Suren,

First, we need to make sure that the plugin has been built correctly, can you please list the content of the `dist` folder? 
It should look like this:

![image](https://github.com/SAP/alm-plug-in-for-grafana/assets/71137661/db1daf5b-58f7-4c15-bb2c-fce0318737be)

You should also make sure that the location of the plugin is correct, can you show me the full path of the dist folder or show me the value of the `plugins`  parameter in your grafana.ini file?
This is the value in my test environment (official Docker Image on Alpine):

![image](https://github.com/SAP/alm-plug-in-for-grafana/assets/71137661/bbf04cc1-fac4-4d65-9fc6-273da8ae3ff4)

Best Regards,

Andrea
