### ISSUE TITLE
SAP ALM and Grafana Cloud

### ISSUE THREAD

**Issue by srclosson** [SAP/alm-plug-in-for-grafana#119]
Hi there!

Was curious about the appetite for getting this ALM integration for SAP signed and into grafana cloud?

**Comment by andreacampo** [comment]
Hello Stephanie,

We would love to sign the plugin. However, I'm certain you understand that this isn't free, especially if the backend technology isn't 'open'. This clashes with our goal to provide the plugin free of charge to our SAP Cloud ALM and Focused Run customers.

Best Regards,

Andrea
