### ISSUE TITLE
install

### ISSUE THREAD

**Issue by BorisTrnka** [SAP/alm-plug-in-for-grafana#33]
Hi, please share signed copy of the plugin with us. Thanks

**Comment by andreacampo** [comment]
Hello Boris, unfortunately we are not allowed to distribute built plugins. You have to build it yourself by executing the steps described in the [README](https://github.com/SAP/alm-plug-in-for-grafana/blob/master/sap-alm-dp-api-datasource/README.md) file in the [Assembly](https://github.com/SAP/alm-plug-in-for-grafana/blob/master/sap-alm-dp-api-datasource/README.md#assembly) section.

**Comment by BorisTrnka** [comment]
Hi,
OK, thanks for the info. So we will test the unsigned version.
