### ISSUE TITLE
install issue

### ISSUE THREAD

**Issue by dlwderegges** [SAP/alm-plug-in-for-grafana#34]
Hi,

we have an issue installing the plugin after compiling it with yarn:

bash-5.1$ cd /var/lib/grafana/plugins
bash-5.1$ ls
sap-alm-dp-api-datasource
bash-5.1$ grafana-cli plugins install sap-alm-dp-api-datasource
Error: ✗ Plugin not found (Grafana v8.4.7 linux-amd64)

It noted in the documentation that we should raise an issue to receive an official plugin version.

Also: will this plugin be available for Azure Managed Grafana in the future?

**Comment by andreacampo** [comment]
Hello, 

unfortunately we are not allowed to distribute built plugins, the readme file has been corrected.
After building the plugin executing the steps described in the [README](https://github.com/SAP/alm-plug-in-for-grafana/blob/master/sap-alm-dp-api-datasource/README.md) file in the [Assembly](https://github.com/SAP/alm-plug-in-for-grafana/blob/master/sap-alm-dp-api-datasource/README.md#assembly) section you can manually copy the newly created dist folder into the created sap-alm-dp-api-datasource in Grafana plugins directory. Then restart your Grafana or Grafana server to discover the plugin.

Starting with Grafana 8, signature verification for unsigned plugins is activated by default. In case the Data Source is not visible or is not working after the restart, add the following parameter to grafana.ini file: allow_loading_unsigned_plugins=sap-alm-dp-api-datasource

As for Azure Managed Grafana support, according to the official [support page](https://azure.microsoft.com/en-us/services/managed-grafana/#faq) custom plugins are not supported.

**Comment by andreacampo** [comment]
Glad to hear that, I am closing the issue then.
