### ISSUE TITLE
Issue with "Complete Time Series with Zeroes" option: additional zeroes

### ISSUE THREAD

**Issue by andreacampo** [SAP/alm-plug-in-for-grafana#57]
Time Series displays additional zeros for the current hour when the option "Complete Time Series with Zeroes" is enabled.

![image](https://user-images.githubusercontent.com/71137661/197539838-a774a518-0368-4170-bcf3-a55a00746d3e.png)

![image](https://user-images.githubusercontent.com/71137661/197539689-0f6014bd-2eef-429a-9694-c1977472912b.png)

**Comment by vienlam** [comment]
This should be fixed in version 1.2.0

**Comment by andreacampo** [comment]
Closing as this is fixed.
