### ISSUE TITLE
Issue when trying to use the ALM plugin : Fetch error: 404 Not Found Instantiating module.js

### ISSUE THREAD

**Issue by superstevor** [SAP/alm-plug-in-for-grafana#99]
Hello, 

I encounter this error message when trying to create a new datasource based on sap-alm-dp-api-datasource : 

_Fetch error: 404 Not Found Instantiating http://localhost:3000/public/plugins/sap-alm-dp-api-datasource/module.js Loading plugins/sap-alm-dp-api-datasource/module_

I'm running grafana 9.4.7. 

I've built the software using : 
Yarn 1.22.19
Node js 18.17.1
Using "yarn build" / "yarn  install". Got a couple of warnings but no errors. 

Any idea of what could be wrong and how to solve it ? 

Thanks & Best regards !

**Comment by vienlam** [comment]
Hi @superstevor,

This only means the build process did not finish successfully, since the module.js does not present.

Which OS are you using? If you are using Windows, you will need WSL and build the plug-in from there. Newer version (from 9 I think) of Grafana data source plug-in development environment works in Linux based system.

**Comment by masterdrake3** [comment]
I confirm what @superstevor wrote: trying to build this package in Windows does not create module.js file (and many others).
I tryed in Debian os and it works.

Still an issue I think.

**Comment by vienlam** [comment]
> I confirm what @superstevor wrote: trying to build this package in Windows does not create module.js file (and many others). I tryed in Debian os and it works.
> 
> Still an issue I think.

Maybe some dependencies are working only in Linux system. This is out of scope for us.
If we work on Windows machine, we can try WSL to build the plug-in.

Best regards,

**Comment by andreacampo** [comment]
For info, this is related to this issue in the grafana-plugin tool: https://github.com/grafana/plugin-tools/issues/931
I am going to prepare a new release with the fix.

**Comment by andreacampo** [comment]
Closed by #112
